name: Health Check pipeline

on:
  schedule:
    - cron: '*/5 * * * *'
  push:
    branches:
      - main

jobs:
  healthcheck:
    runs-on: ubuntu-22.04
    steps:
      - name: Check the deployed service URL
        uses: jtalk/url-health-check-action@v4
        with:
          url: ${{ secrets.DEPLOYED_APP_URL }}/health-fail
          follow-redirect: true
          max-attempts: 3
          retry-delay: 10s
          retry-all: true
      - name: Discord Notify Error
        uses: rjstone/discord-webhook-notify@v2
        if: ${{ failure() }}
        with:
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
          severity: error
          details: Health Check failed!
